version: "3.7"
networks:
  shared-network:
    driver: bridge
    ipam:
      driver: default
services:
  api:
      container_name: api
      restart: always
      pid: "host"
      networks:
        - shared-network
      hostname: "host"
      ipc: host
      image: 'neversitup'
      ports:
        - "32405:8080"